data:
  t_max: 2.0
  lx: 2.0
  ly: 2.0       # Used for implementing 2D
  alpha: 0.01

data_size:
    n_int: 1000
    n_ic: 600
    n_bc: 300

training:
  batch_size : 256
  learning_rate: 0.001
  epochs: 10000

hardware:
  device: "mps"